DROP TABLE slrkadr  IF EXISTS;

CREATE TABLE slrkadr 
   ( id INTEGER identity primary key,
idnationality DECIMAL,
idlanguage DECIMAL,
idcountry DECIMAL,
idcitizenship DECIMAL,
sfirstname VARCHAR(20),
ssecondname VARCHAR(40),
sthirdname VARCHAR(20),
snm VARCHAR(254),
lsex VARCHAR(1),
dbirthdate DATE,
sbirthregion VARCHAR(255),
sbirtharea VARCHAR(255),
sbirthtown VARCHAR(255),
sfirstnamerp VARCHAR(20),
ssecondnamerp VARCHAR(40),
sthirdnamerp VARCHAR(20),
sfirstnamedp VARCHAR(20),
ssecondnamedp VARCHAR(40),
sthirdnamedp VARCHAR(20),
semail VARCHAR(255),
sinn VARCHAR(12),
spfnumber VARCHAR(14),
spfcategory VARCHAR(20),
sgni VARCHAR(10),
codct DECIMAL,
idalientcategory DECIMAL,
lworker VARCHAR(1),
ddeathdate DATE,
laltfondprc VARCHAR(1),
idcreator DECIMAL,
ideditor DECIMAL,
dcreatedatetime DATE,
deditdatetime DATE,
dbeginoptionalpfr DATE,
dendoptionalpfr DATE,
nspeciallabel DECIMAL,
sinnino VARCHAR(12) );

CREATE INDEX slrkadr_idx ON slrkadr (id);

